<?php

/** @var $viewModel \Perspective\CategoryProduct\ViewModel\CategoryProductModel */
/** @var $escaper \Magento\Framework\Escaper */

$viewModel = $block->getViewModel();

//var_dump($viewModel->getCustomerCollection());
$categoryList = $viewModel ->getAllSystemCategory();

if ($categoryList->getTotalCount()) {
    foreach ($categoryList->getItems() as $category){
        var_dump($category->getName());
    }
}