<?php
/** @var \Perspective\Theme10Ex1\Block\Template $block */
?>

<?php

$viewModel = $block->getData('view_model');

############### Ex 3.1 ###############
/* $collection = $viewModel->getPostCollection();
foreach ($collection as $item) {
    echo "<pre>";
    print_r($item->getData());
    echo "</pre>";
} */
######################################

############### Ex 3.2 ###############
/* $customerReview = $viewModel->getGucsotmerReview();
if ($customerReview && count($customerReview) > 0) {
    foreach ($customerReview AS $review) {
       echo "Name: " . $review->getData("Name") . "<br>";
       echo "Email: " . $review->getData("Email") . "<br>";
       echo "Review: " . $review->getData("TextRev");
    }
} */
######################################

############### Ex 3.3 ###############
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$collection = $viewModel->getPostCollection();
$categoryId = 14;
$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory')->create();
$category = $categoryFactory->load($categoryId);
 
$products = $category->getProductCollection()
                    ->addAttributeToSelect('*');

foreach ($products as $product) {
    $productTemp = $product->getId();
    foreach ($collection as $item) {
        $productIdTemp = $item->getData("IDProd");
        if ($productTemp !== $productIdTemp) 
        {

        } else {
            echo "Product ID: " . $item->getData("IDProd") . "<br />";
            echo "Product Sku: " . $product->getData("sku") . "<br />";
            echo "Product Price: " . round($product->getData("price"),2) . " $<br />";
            echo "Product Category Name: " . $category->getData("url_key") . "<br />";
            echo "Product Review: " . $item->getData("TextRev") . "<br />";
            #echo "Product Url: " . $product->getProductUrl() . "<br />";
            $productImages = $viewModel->getProductImages($item->getData("IDProd"));
            foreach ($productImages as $image) {
                echo "Product Url: " . $image->getUrl() . "<br/>";
                echo "<img src=" . $image->getUrl() . " width='150' height='150' />" . "<br/>";
            }
            #var_dump($product->getData());
        }
    };
}
######################################