<?php

/** @var $viewModel \Perspective\CustomerModule\ViewModel\CustomerModel */
/** @var $escaper \Magento\Framework\Escaper */

$viewModel = $block->getData('view_model');

$customerCollection = $viewModel->getCustomer();

 if ($customerCollection && count($customerCollection) > 0) {
     foreach ($customerCollection AS $customer) {
        echo "<b>Имя: </b>" . $customer->getFirstname()."<br/>";
        echo "<b>Фамилия: </b>" . $customer->getLastname()."<br/>";
        echo "<b>Email: </b>" . $customer->getEmail()."<br/>";
    
        //echo var_dump ($customer->getData());
     }
 }
 ?>