<?php
/** @var \Perspective\Theme5Ex1\Block\Template $block */
?>

<?php 

$viewModel = $block->getData('view_model');

############## Ex 1.1 ##############
/* $productId = 2041; // YOUR PRODUCT ID
$product = $viewModel->getProductById($productId);
 
// for current product
// $product = $viewModel->getCurrentProduct();
 
$categoryIds = $product->getCategoryIds();

$categories = $viewModel->getCategoryCollection()
                    ->addAttributeToFilter('entity_id', $categoryIds);
                    
foreach ($categories as $category) {
    echo $category->getName() . '<br>';
} */
#######################################

############## Ex 1.2 ##############
/* $productId = [];
$catalogRule = $viewModel->getAllActiveCatalogRule();
foreach($catalogRule as $rule) {
    #var_dump($rule->getData());
    #echo ($rule->getId());
    #echo "<br>";
    $productId = $rule->getId();
    $product = $viewModel->getProductById($productId);
    echo $product->getName() . '<br>';
} */
#######################################

############## Ex 1.3 ##############
/* $ids = [1,2,3];
$categoryProducts = $viewModel->getProductCollectionByCategories($ids);
foreach ($categoryProducts as $product) {
    echo $product->getName() . ' - ' . $product->getProductUrl() . '<br />';
} */
#######################################

############## Ex 1.4 ##############
$collection = $viewModel->getProductCollection();
foreach ($collection as $_product) {
    echo $_product->getName() . ' - ' . $_product->getProductUrl() . '<br />';
#######################################
}