<?php
/** @var \Perspective\Theme13Ex2\Block\Template $block */

$viewModel = $block->getViewModel();

$currentProduct = $viewModel->getCurrentProduct();

$id = $currentProduct->getId();
$_productStock = $viewModel->getStockItem($id);

$Y = $_productStock->getQty();

if ($_productStock->getQty() < $viewModel->getX()) :
    echo "<h3 style='color:black'>" . "Продукт заканчивается" . "</h3>";
    echo "<br>";
    echo "</h3>" . "<h3 style='color:red'>" . "Осталось " . $Y . " шт." . "</h3>";
endif;
