<?php
/** @var \Perspective\Theme5Ex4\Block\Template $block */
?>

<?php

$viewModel = $block->getData('view_model');

############## Ex 4.1 ##############
$childrenItems = $viewModel->getChildrenItems();
    foreach ($childrenItems as $itemCh) {
        echo ($itemCh->getData('sku') . "<br>");
    }
#######################################

############## Ex 4.2 ##############
/* $sku = '24-WG085_Group';
$childProductsData = $viewModel->getChildItemsFromGroupedProduct($sku);
foreach ($childProductsData as $itemG) {
    echo ($itemG->getData('sku') . "<br>");
} */
#######################################