<?php
/** @var \Perspective\SessionWork\Block\Template $block */

$block->getCatalogSession()->setMyName('Perspective');
echo $block->getCatalogSession()->getMyName() . '<br />'; // output: Perspective

$block->getCheckoutSession()->setTestData('Hello World');
echo $block->getCheckoutSession()->getTestData() . '<br />'; // output: Hello World

$block->getCheckoutSession()->setTestHello('Test Hello Value');
echo $block->getCheckoutSession()->getTestHello() . '<br />'; // output: Test Hello Value
?>