<?php
/** @var \Perspective\Theme5Ex2\Block\Template $block */
?>

<?php

$viewModel = $block->getData('view_model');

############## Ex 2.1 ##############
/* $id = 2041;
$_productStock = $viewModel->getStockItem($id);
$product = $viewModel->getProductById($id);

echo '<b>Name:</b> ' . $product->getName(); echo '<br />';
echo '<b>Id:</b> ' . $product->getId(); echo '<br />';
echo '<b>Qty:</b> ' . $_productStock->getQty(); echo '<br />';
echo '<b>MinQty:</b> ' . $_productStock->getMinQty(); echo '<br />';
echo '<b>MinSaleQty:</b> ' . $_productStock->getMinSaleQty(); echo '<br />';
echo '<b>MaxSaleQty:</b> ' . $_productStock->getMaxSaleQty(); echo '<br />';
echo '<b>IsInStock:</b> ' . $_productStock->getIsInStock(); echo '<br />'; */
#######################################

############## Ex 2.2 ##############
/* $id = 271;
$productImage = $viewModel->getProductImageUrl($id);
echo "URL картинки: " . $productImage . '<br />';
echo "Ширина картинки: " . $viewModel->getImageOriginalWidth($id, 'product_page_image_medium') . '<br />'; 
echo "Высота картинки: " . $viewModel->getImageOriginalHeight($id, 'product_page_image_medium') . '<br />'; */
#######################################

############## Ex 2.3 ##############
/* var_dump ($viewModel->getCustomerCollection()->getData()); */
#######################################

############## Ex 2.4 ##############
/* $ordersCollection = $viewModel->getOrderCollection();
if ($ordersCollection && count($ordersCollection) > 0) {
    foreach ($ordersCollection AS $orders) {
        echo "<hr>";
        echo "Статус заказа: " . $orders->getStatus()."<br/>";
        echo "Номер заказа: " . $orders->getEntity_id()."<br/>";        
        echo "Сумма доставки: " . round($orders->getShipping_amount(), 2) . "$" ."<br/>";
        echo "Сумма заказа: " . round($orders->getTotal_paid(), 2) . "$" ."<br/>";
        echo "<br>";
        echo "Почта заказчика: " . $orders->getCustomer_email()."<br/>";
        echo "Имя заказчика: " . $orders->getCustomer_firstname()."<br/>";
        echo "Фамилия заказчика: " . $orders->getCustomer_lastname()."<br/>";
        echo "ID заказчика: " . $orders->getCustomer_id()."<br/>";
    }
} */
#######################################

############## Ex 2.5 ##############
/* $customerGroupCollection = $viewModel->getCustomerGroups();

foreach ($customerGroupCollection AS $customerGroup) {
    echo "<b>Название группы:</b> " . array_values($customerGroup)[1];
    echo "<br>";
} */
#######################################

############## Ex 2.6 ##############
/* $payments = $viewModel->getAllPaymentMethodsList();

foreach ($payments as $payment) {
    echo ($payment);
    echo "<br>";
} */
#######################################

############## Ex 2.7 ##############
$allShipping = $viewModel->getAllShippingMethods(); 
foreach($allShipping as $shipping) { 
    
        echo ($shipping['label']); 
        echo "<br>";
}
#######################################
